version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: "Dockerfile"
    container_name: ng_speed_app
    expose:
       - 8080
networks:
  default:
    external:
      name: nginx-proxy
